### ISSUE TITLE
userStory - Homepage Featured Recipes

### ISSUE THREAD

**Issue by yoricktf** [yoricktf/VeganPlusButter#1]
## Value proposition

As an User
I want to see the home page with recipes
So that I can get an overview of the featured recipes

## Description

![Image](https://user-images.githubusercontent.com/26628713/223392324-70a6430c-e356-43c7-b7dd-5a23c8d5a29d.png)

## Acceptance criteria

- [ ] display recipe cards with the _featured_ property set to true
- [ ] the card should display the first Image
- [ ] the card should display the Name
- [ ] the card should display the tags

## Tasks

- [ ] filter recipes with the _featured_ boolean set to true, and map over the results to make the cards
- [ ] create a card component to be use don the main page
