### ISSUE TITLE
UserStory - Search

### ISSUE THREAD

**Issue by yoricktf** [yoricktf/VeganPlusButter#2]
## Value proposition

As an User
I want to search all Recipes
So that I can find specfic recipes

## Description

![Image](https://user-images.githubusercontent.com/26628713/223394755-72fffd1e-c344-4ba1-96e3-9296763089fa.png)

## Acceptance criteria

- [ ] should display _largeCardComponent_
- [ ] In the largeCardComponent, the name of the recipe is displayed
- [ ] In the largeCardComponent, the first image is displayed
- [ ] In the largeCardComponent, the tags are displayed
- [ ] In the largeCardComponent, the number of comments are displayed
- [ ] In the largeCardComponent, the number of times it has been favorited are displayed
- [ ] it is a link to the show page

## Tasks

- [ ] make the largeCardComponent
- [ ] filter the recipes based on my input and map the results in the large card component
