### ISSUE TITLE
UserStory - Show/Details Page

### ISSUE THREAD

**Issue by yoricktf** [yoricktf/VeganPlusButter#7]
## Value proposition

As an user
I want to go to the Show/details page
So that I can see how a recipe is made

## Description

![Image](https://user-images.githubusercontent.com/26628713/223397134-e1130f59-9386-4799-ad61-b25a0aa05119.png)

## Acceptance criteria

- [ ] show the details from a specfic recipe
- [ ] display all the important recipe properties (title, ingredients, method, Images, tags, difficulty, cooktime, preptime, servingsize)

## Tasks

- [ ] make a new page using the _ID_
- [ ] find the specific recipe based on the _ID_ in the URL
- [ ] display that recipes charecteristics
